language: php

matrix:
  include:
  - php: 7.1
    env: DB=sqlite
  fast_finish: true

sudo: false

install: travis_retry composer install

script: composer ci

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always
