#!/bin/env php
<?php

use Symfony\Component\Process\Process;
use WMDE\Fundraising\Deployment\TopLevelFactory;

require_once __DIR__ . '../vendor/autoload.php';

call_user_func( function() {
	$command = new Process(
		'ansible-playbook -i inventory/production deployment.yml',
		empty( $GLOBALS['argv'][1] ) ? null : $GLOBALS['argv'][1]
	);

	TopLevelFactory::newFromConfig()->newDeployer( 'production' )->run( $command );
} );
