#!/bin/env php
<?php

use Symfony\Component\Process\Process;
use WMDE\Fundraising\Deployment\Deployer;
use WMDE\Fundraising\Deployment\PDOReleaseState;

require_once __DIR__ . '../vendor/autoload.php';

define( 'DB_DSN', __DIR__ . '/../var/releases.sqlite' );
define( 'DEPLOY_COMMAND', 'ansible-playbook -i inventory/production deployment.yml' );
define( 'BRANCH_NAME', 'production' );

if ( !file_exists( DB_DSN ) ) {
	exit(1);
}

$cwd = empty( $argv[1] ) ? null : $argv[1];

$releaseState = new PDOReleaseState( new \PDO( DB_DSN ), BRANCH_NAME );
$deployer = new Deployer( $releaseState  );
$command = new Process( DEPLOY_COMMAND, $cwd );
$deployer->run( $command );